POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "Orzu",
  "last_name": "Mirzayev",
  "username": "orzu2",
  "password": "1234"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "orzu",
  "password": "1234"
}